apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: cnv-sriov-profile 
spec:
  cpu:
    isolated: "8-47"
    reserved: "0-7"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 8
  realTimeKernel:
    enabled: false 
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: "" 

