apiVersion: v1
kind: Pod
metadata:
  name: testpmd
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-intel-west,sriov-intel-east
spec:
  restartPolicy: Never
  containers:
  - name: testpmd 
    image: docker.io/cscojianzhan/perf-tools-prebuild-dpdk
    #imagePullPolicy: IfNotPresent
    imagePullPolicy: Always
    env:
    - name: ring_size
      value: "2048"
    securityContext:
      capabilities:
      privileged: true
    volumeMounts:
    - mountPath: /dev/hugepages
      name: hugepage
    - mountPath: /sys
      name: sys
    - mountPath: /dev
      name: dev
    resources:
      limits:
        cpu: 4
        hugepages-1Gi: 2Gi
        memory: 2Gi
      requests:
        cpu: 4
        hugepages-1Gi: 2Gi
        memory: 2Gi
  volumes:
  - name: sys
    hostPath:
      path: /sys
  - name: dev
    hostPath:
      path: /dev
  - name: hugepage
    emptyDir:
      medium: HugePages


