apiVersion: v1
kind: Pod
metadata:
  name: uperf-master
spec:
  restartPolicy: Never
  containers:
  - name: uperf-master
    image: quay.io/jianzzha/perf-tools 
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: https://github.com/jianzzha/container-tools.git
    - name: tool
      value: uperf
    - name: mode 
      value: manual 
    securityContext:
      privileged: true
    resources:
      limits:
        cpu: 4 
        memory: 4Gi
      requests:
        cpu: 4 
        memory: 4Gi
  nodeSelector:
    kubernetes.io/hostname: "goblin-worker-1" 

