apiVersion: v1 
kind: Pod 
metadata:
  name: sysjitter 
spec:
  restartPolicy: Never 
  containers:
  - name: container-perf-tools 
    image:  docker.io/cscojianzhan/container-perf-tools
    env:
    - name: tool
      value: "sysjitter"
    - name: trace
      value: "false"
    - name: RUNTIME_SECONDS 
      value: "60"
    - name: THRESHOLD_NS
      value: "10"
    securityContext:
    volumeMounts:
    - mountPath: /tmp
      name: results-volume
  volumes:
  - name: results-volume
    hostPath:
      path: /tmp
  
