apiVersion: v1 
kind: Pod 
metadata:
  name: sysjitter 
spec:
  restartPolicy: Never 
  containers:
  - name: container-perf-tools 
    image: quay.io/jianzzha/perf-tools
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: https://github.com/jianzzha/container-tools.git
    - name: tool
      value: "sysjitter"
    - name: RUNTIME_SECONDS 
      value: "3600"
    - name: THRESHOLD_NS
      value: "200"
    - name: USE_TASKSET
      value: "n"
    - name: DISABLE_CPU_BALANCE
      value: "y"
      # DISABLE_CPU_BALANCE requires privileged=true
    - name: manual
      value: "n"
    securityContext:
      privileged: true
      #capabilities:
      #  add:
      #    - SYS_NICE
      #    - IPC_LOCK
      #    - SYS_RAWIO
    resources:
      limits:
        cpu: 9
        memory: "8000Mi"
      requests:
        cpu: 9
        memory: "8000Mi"
  nodeSelector:
    node-role.kubernetes.io/worker-rt: ""

