apiVersion: v1 
kind: Pod 
metadata:
  name: oslat
spec:
  restartPolicy: Never 
  containers:
  - name: container-perf-tools 
    image: quay.io/jianzzha/perf-tools
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: https://github.com/tc-wilson/container-tools.git
    - name: tool
      value: "oslat"
    - name: RUNTIME_SECONDS 
      value: "600"
    - name: RTPRIO
      value: "1"
    - name: USE_TASKSET
      value: "n"
    - name: DISABLE_CPU_BALANCE
      value: "y"
      # DISABLE_CPU_BALANCE requires privileged=true
    - name: manual
      value: "n"

    securityContext:
      privileged: true
      #capabilities:
      #  add:
      #    - SYS_NICE
      #    - IPC_LOCK
      #    - SYS_RAWIO
    resources:
      limits:
        cpu: 9
        memory: "32Gi"
      requests:
        cpu: 9
        memory: "32Gi"
  nodeSelector:
    node-role.kubernetes.io/worker: ""
