apiVersion: v1 
kind: Pod 
metadata:
  name: sysjitter 
spec:
  restartPolicy: Never 
  containers:
  - name: container-perf-tools 
    image: quay.io/jianzzha/perf-tools
    env:
    - name: GIT_URL
      value: https://github.com/jianzzha/container-tools.git
    - name: tool
      value: "sysjitter"
    - name: RUNTIME_SECONDS 
      value: "5"
    - name: THRESHOLD_NS
      value: "200"
    - name: USE_TASKSET
      value: "y"
    - name: DISABLE_CPU_BALANCE
      value: "y"
      # DISABLE_CPU_BALANCE requires privileged=true
    securityContext:
      privileged: true
      #capabilities:
      #  add:
      #    - SYS_NICE
      #    - IPC_LOCK
      #    - SYS_RAWIO
    resources:
      limits:
        cpu: 4
        memory: "400Mi"
      requests:
        cpu: 4
        memory: "400Mi"
