apiVersion: v1
kind: Pod
metadata:
  name: testpmd
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-mlx-west,sriov-mlx-east
spec:
  restartPolicy: Never
  hostNetwork: true
  containers:
  - name: testpmd 
    image: quay.io/jianzzha/perf-tools 
    #imagePullPolicy: IfNotPresent
    imagePullPolicy: Always
    env:
    - name: GIT_URL
      value: https://github.com/jianzzha/fork-container-tools.git
    - name: tool
      value: testpmd
    - name: ring_size
      value: "2048"
    - name: manual
      value: 'y'
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/hugepages
      name: hugepage
    - mountPath: /sys
      name: sys
    - mountPath: /dev
      name: dev
    resources:
      limits:
        cpu: 4
        hugepages-1Gi: 2Gi
        memory: 2Gi
      requests:
        cpu: 4
        hugepages-1Gi: 2Gi
        memory: 2Gi
  volumes:
  - name: sys
    hostPath:
      path: /sys
  - name: dev
    hostPath:
      path: /dev
  - name: hugepage
    emptyDir:
      medium: HugePages


