apiVersion: v1 
kind: Pod 
metadata:
  name: sysjitter 
spec:
  restartPolicy: Never 
  containers:
  - name: container-perf-tools 
    image: quay.io/jianzzha/perf-tools
    env:
    - name: GIT_URL
      value: https://github.com/jianzzha/fork-container-tools.git
    - name: tool
      value: "sysjitter"
    - name: RUNTIME_SECONDS 
      value: "60"
    - name: THRESHOLD_NS
      value: "200"
    - name: USE_TASKSET
      value: "y"
    - name: DISABLE_CPU_BALANCE
      value: "y"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /tmp
      name: results-volume
    resources:
      limits:
        cpu: 4
        memory: "400Mi"
      requests:
        cpu: 4
        memory: "400Mi"
  volumes:
  - name: results-volume
    hostPath:
      path: /tmp
  
