apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cnv
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-cnv-operatorgroup
  namespace: openshift-cnv 
spec:
  targetNamespaces:
  - openshift-cnv
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-cnv-subscription
  namespace: openshift-cnv
spec:
  channel: "2.3"
  name: kubevirt-hyperconverged  
  source: redhat-operators
  sourceNamespace: openshift-marketplace
