apiVersion: hco.kubevirt.io/v1alpha1
kind: HyperConverged
metadata:
  finalizers:
  - hyperconvergeds.hco.kubevirt.io
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  BareMetalPlatform: true
